// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NbaLibrary.Models
{
    public partial class Jersey
    {
        public Jersey()
        {
            purchase = new HashSet<purchase>();
        }

        public Jersey(int jerseyid, string gender, string size, string name, int number)
        { 
            JerseyID = jerseyid;
            Gender = gender;
            Size = size;
            Name = name;
            Number = number;
        }

        public int JerseyID { get; set; }
        public string Gender { get; set; }
        public string Size { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public int? TeamID { get; set; }
        public double? price { get; set; }

        public virtual Team Team { get; set; }
        public virtual ICollection<purchase> purchase { get; set; }

        
    }
}